// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Word from "./Word.bs.js";
import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";

function getRandomValue(arr) {
  var i = Js_math.random_int(0, arr.length - 1 | 0);
  return Caml_array.get(arr, i);
}

function getRandomWord(param) {
  return getRandomValue(Word.words);
}

export {
  getRandomValue ,
  getRandomWord ,
  
}
/* No side effect */
