// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function incr(prev) {
  return prev + 1 | 0;
}

function decr(prev) {
  return prev - 1 | 0;
}

function Counter(Props) {
  var match = React.useState(function () {
        return 0;
      });
  var setCount = match[1];
  var countStr = "Count: " + String(match[0]);
  return React.createElement(React.Fragment, undefined, React.createElement("h2", undefined, "Counter"), React.createElement("h3", undefined, countStr), React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(setCount, incr);
                        })
                    }, "+")), React.createElement("div", undefined, React.createElement("button", {
                      onClick: (function (param) {
                          return Curry._1(setCount, decr);
                        })
                    }, "-")));
}

var make = Counter;

export {
  incr ,
  decr ,
  make ,
  
}
/* react Not a pure module */
