// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./components/Game.bs.js";
import * as React from "react";

function App(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Hangman"), React.createElement(Game.make, {}));
}

var make = App;

export {
  make ,
  
}
/* Game Not a pure module */
