// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Counter from "./components/Counter.bs.js";
import * as RandomWordGenerator from "./utils/RandomWordGenerator/RandomWordGenerator.bs.js";

function App(Props) {
  var randomWord = RandomWordGenerator.getRandomWord(undefined);
  return React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, "Hangman"), React.createElement(Counter.make, {}), React.createElement("h3", undefined, randomWord));
}

var make = App;

export {
  make ,
  
}
/* react Not a pure module */
